sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run react-test npm test -- --coverage

after_success:
 - docker build -t kaname87/multi-client ./client
 - docker build -t kaname87/multi-nginx ./nginx
 - docker build -t kaname87/multi-server ./server
 - docker build -t kaname87/multi-worker ./worker
 # Login to docker hub
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # Push to docker hub
 - docker push kaname87/multi-client
 - docker push kaname87/multi-nginx
 - docker push kaname87/multi-server
 - docker push kaname87/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-066864504552
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY